var fruitName;
fruitName = "Cristian";
console.log(fruitName);


var lastName = "Davis"; // declara y asignar
lastName = "Juan"
console.log(lastName);

var firstName = "Jazmin"; // declarar y asignar
var firstName = "Amor";// reasignar
console.log(firstName);

// with let

let frui = "Apple"
frui = "Kiwi"
let frui = "banana"

// with const

const animal = "dog"
animal = "cat"

const products = [];
products.push("Apple")
console.log(products);
products.pop("Apple")
console.log(products);

